/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package carshowroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author shamaz
 */
public class JFrameMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMainMenu
     */
    public JFrameMainMenu() {
        initComponents();
        showCustomer();
//        Show_Customers_In_JTable();
    }
 
     public ArrayList<User> getCustomerList()
   {
       ArrayList<User>Customerlist = new ArrayList<User>();
      try
        {
           ClassDBConnectivity databaseConnectivity = new ClassDBConnectivity();
            Connection connection = databaseConnectivity.getDatabaseConnectivity();
//            Statement statement = connection.createStatement();
//            
            String query21 = "select * from Customer_T";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query21);
           User cust;
           while(rs.next())
           {
               cust = new User(rs.getString("CustomerID"),rs.getString("FirstName"),rs.getString("LastName"),rs.getInt("PhoneNumber"),rs.getString("CustomerAddress"),rs.getString("CustomerCity"),rs.getString("CustomerState"),rs.getString("CustomerCountry"),rs.getString("CustomerPostalCode"));
               Customerlist.add(cust);
           }
            
        }
       catch(Exception e)
        {
            System.out.println(""+e);
            JOptionPane.showMessageDialog(null,e);
                   
        }
       
      return Customerlist;
   }
    
    public void showCustomer()
    {
        ArrayList<User>  listintablecustomer = getCustomerList();
        DefaultTableModel modelCustomer = (DefaultTableModel)jTableShowAllDataCustomer.getModel();
        
        Object[] row = new Object[9];
       for(int i = 0; i < listintablecustomer.size(); i++)
       {
           row[0] = listintablecustomer.get(i).getCustomerID();
           row[1] = listintablecustomer.get(i).getFirstName();
           row[2] = listintablecustomer.get(i).getLastName();
           row[3] = listintablecustomer.get(i).getPhoneno();
           row[4] = listintablecustomer.get(i).getAddress();
           row[5] = listintablecustomer.get(i).getState();
           row[6] = listintablecustomer.get(i).getPostelcode();
           row[7] = listintablecustomer.get(i).getCity();
           row[8] = listintablecustomer.get(i).getCountry();
           
           
           
           modelCustomer.addRow(row);
       }
    }
    
    public void executeSQLQuery(String queryCustomer,String message)
    {
              try
        {
            ClassDBConnectivity databaseConnectivity = new ClassDBConnectivity();
            Connection connection = databaseConnectivity.getDatabaseConnectivity();
       //     Statement statement = connection.createStatement();
//         
           Statement st;
            try
            {
               st = connection.createStatement();
               if(st.executeUpdate(queryCustomer) == 1)
               {
                   
                 DefaultTableModel modelCustomer = (DefaultTableModel)jTableShowAllDataCustomer.getModel();
                 modelCustomer.setRowCount(0);
                 showCustomer();
                 
                 JOptionPane.showMessageDialog(null, "Data "+message+" Successfully");
               }
               else 
               {
                   JOptionPane.showMessageDialog(null, "Data not "+message+ " " );
                   
               }
               
            }
             catch(Exception e)
        {
            System.out.println(""+e);
            JOptionPane.showMessageDialog(null,"Primary Key Mismatch.Please Choose Unique Primary Key");
                   
        }
           
            
            
        }
       catch(Exception e)
        {
            System.out.println(""+e);
            JOptionPane.showMessageDialog(null, e);
                   
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCustomerID = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFirstName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldProvince = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPostelCode = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableShowAllDataCustomer = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Car Dealing Management System");
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMER");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(480, 10, 160, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/LOG.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(0, 0, 90, 59);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/home.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(1100, 0, 100, 59);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CUSTOMER ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 30, 110, 17);

        jTextFieldCustomerID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCustomerIDKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldCustomerID);
        jTextFieldCustomerID.setBounds(130, 30, 110, 20);

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLastNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldLastName);
        jTextFieldLastName.setBounds(130, 110, 110, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("LAST NAME");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 110, 110, 17);

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFirstNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldFirstName);
        jTextFieldFirstName.setBounds(130, 70, 110, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("FIRST NAME");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 70, 110, 17);

        jTextFieldPhoneNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneNoKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneNo);
        jTextFieldPhoneNo.setBounds(130, 150, 110, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("PHONE NO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 150, 110, 17);

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldAddress);
        jTextFieldAddress.setBounds(130, 190, 110, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ADDRESS");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 190, 110, 17);

        jTextFieldCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCityKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldCity);
        jTextFieldCity.setBounds(390, 70, 110, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("CITY");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(270, 70, 110, 17);

        jTextFieldProvince.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldProvince.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldProvinceKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldProvince);
        jTextFieldProvince.setBounds(130, 230, 110, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("STATE");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 230, 110, 17);

        jTextFieldCountry.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCountryKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldCountry);
        jTextFieldCountry.setBounds(390, 110, 110, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("COUNTRY");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(270, 110, 110, 17);

        jTextFieldPostelCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldPostelCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPostelCodeKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldPostelCode);
        jTextFieldPostelCode.setBounds(390, 30, 110, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("POSTEL CODE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(270, 30, 110, 17);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("View All Customer Data");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(250, 10, 180, 17);

        jTableShowAllDataCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "First Name", "Last Name", "Phone No", "Address", "State", "Postel Code", "City", "Country"
            }
        ));
        jTableShowAllDataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableShowAllDataCustomerMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableShowAllDataCustomer);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(0, 30, 620, 400);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/insert.png"))); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/delete.jpg"))); // NOI18N
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/update.png"))); // NOI18N
        jButton7.setText("Update");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carshowroom/clear.png"))); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
         String queryCustomer = "DELETE FROM Customer_T WHERE CustomerID = '"+jTextFieldCustomerID.getText()+"'";
         executeSQLQuery(queryCustomer,"Deleted");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new JFrameMain().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//       setVisible(false);
//       new JFrameLogIn().setVisible(true); 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String queryCustomer = "insert into Customer_T(CustomerID,FirstName,LastName,PhoneNumber,CustomerCity,CustomerAddress,CustomerState,CustomerCountry,CustomerPostalCode) values('"+jTextFieldCustomerID.getText()+"','"+jTextFieldFirstName.getText()+"','"+jTextFieldLastName.getText()+"','"+jTextFieldPhoneNo.getText()+"','"+jTextFieldAddress.getText()+"','"+jTextFieldCity.getText()+"','"+jTextFieldProvince.getText()+"','"+jTextFieldCountry.getText()+"','"+jTextFieldPostelCode.getText()+"') ";
        executeSQLQuery(queryCustomer,"Inserted");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String queryCustomer = "update Customer_T set FirstName='"+jTextFieldFirstName.getText()+"',LastName='"+jTextFieldLastName.getText()+"',PhoneNumber='"+jTextFieldPhoneNo.getText()+"',CustomerCity='"+jTextFieldCity.getText()+"',CustomerState='"+jTextFieldProvince.getText()+"'CustomerCountry='"+jTextFieldCountry.getText()+"',CustomerPostalCode='"+jTextFieldPostelCode.getText()+"' where CustomerID='"+jTextFieldCustomerID.getText()+"'" ;
        executeSQLQuery(queryCustomer,"Updated");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTextFieldAddress.setText("");
        jTextFieldCity.setText("");
        jTextFieldCountry.setText("");
        jTextFieldCustomerID.setText("");
        jTextFieldFirstName.setText("");
        jTextFieldLastName.setText("");
        jTextFieldPhoneNo.setText("");
        jTextFieldPostelCode.setText("");
        jTextFieldProvince.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTableShowAllDataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableShowAllDataCustomerMouseClicked
              int i = jTableShowAllDataCustomer.getSelectedRow();
        TableModel modelCustomer = jTableShowAllDataCustomer.getModel();
        jTextFieldCustomerID.setText(modelCustomer.getValueAt(i,0).toString());
        jTextFieldFirstName.setText(modelCustomer.getValueAt(i,1).toString());
        jTextFieldLastName.setText(modelCustomer.getValueAt(i,2).toString());
        jTextFieldPhoneNo.setText(modelCustomer.getValueAt(i,3).toString());
        jTextFieldAddress.setText(modelCustomer.getValueAt(i,4).toString());
        jTextFieldProvince.setText(modelCustomer.getValueAt(i,5).toString());
        jTextFieldPostelCode.setText(modelCustomer.getValueAt(i,6).toString());
        jTextFieldCity.setText(modelCustomer.getValueAt(i,7).toString());
        jTextFieldCountry.setText(modelCustomer.getValueAt(i,8).toString());
    }//GEN-LAST:event_jTableShowAllDataCustomerMouseClicked

    private void jTextFieldFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameKeyPressed
  jTextFieldFirstName.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in First Name" );
            String textFirstName = jTextFieldFirstName.getText();
            evt.setKeyCode(8);
        }  
        


        if(evt.getKeyCode() == 10)
        {
            jTextFieldLastName.requestFocus(true);
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameKeyPressed

    private void jTextFieldLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLastNameKeyPressed
         jTextFieldLastName.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in Last Name" );
            String textFirstName = jTextFieldLastName.getText();
            evt.setKeyCode(8);
        }
        


        if(evt.getKeyCode() == 10)
        {
            jTextFieldPhoneNo.requestFocus(true);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameKeyPressed

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
          jTextFieldAddress.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in Address" );
            String textFirstName = jTextFieldAddress.getText();
            evt.setKeyCode(8);
        }
        


        if(evt.getKeyCode() == 10)
        {
            jTextFieldProvince.requestFocus(true);
     }
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldProvinceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProvinceKeyPressed
         jTextFieldProvince.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in State" );
            String textFirstName = jTextFieldProvince.getText();
            evt.setKeyCode(8);
        } 



        if(evt.getKeyCode() == 10)
        {
            jTextFieldPostelCode.requestFocus(true);
     }

// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProvinceKeyPressed

    private void jTextFieldCityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCityKeyPressed
  jTextFieldCity.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in City" );
            String textFirstName = jTextFieldCity.getText();
            evt.setKeyCode(8);
        }       



        if(evt.getKeyCode() == 10)
        {
            jTextFieldCountry.requestFocus(true);
     }        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityKeyPressed

    private void jTextFieldCountryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCountryKeyPressed
         jTextFieldCountry.getText();
        if(evt.getKeyCode() > 47 && evt.getKeyCode()< 59)
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Digits are not allowed in Country" );
            String textFirstName = jTextFieldCountry.getText();
            evt.setKeyCode(8);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountryKeyPressed

    private void jTextFieldPostelCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPostelCodeKeyPressed

 if((evt.getKeyCode() < 48 || evt.getKeyCode() > 57))
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Alphabet or Special Characters are not allowed in Postel Code");
            jTextFieldPostelCode.setText("");
        }
 


        if(evt.getKeyCode() == 10)
        {
            jTextFieldCity.requestFocus(true);
     }
 // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPostelCodeKeyPressed

    private void jTextFieldPhoneNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoKeyPressed

 if((evt.getKeyCode() < 48 || evt.getKeyCode() > 57))
        {
            javax.swing.JOptionPane.showMessageDialog(null,"Alphabet or Special Characters are not allowed in Phone No");
            jTextFieldPhoneNo.setText("");
        }      
 


        if(evt.getKeyCode() == 10)
        {
            jTextFieldAddress.requestFocus(true);
     }
 // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNoKeyPressed

    private void jTextFieldCustomerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCustomerIDKeyPressed



        if(evt.getKeyCode() == 10)
        {
            jTextFieldFirstName.requestFocus(true);
     }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCustomerIDKeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
 int option;
     if( SwingUtilities.isLeftMouseButton(evt) )
        {   
            option = javax.swing.JOptionPane.showConfirmDialog(null,"Are you sure you want to Logout?");
            if (option==0)
            {
                setVisible(false);
             new JFrameLogIn().setVisible(true);
             
            }
            else if (option==1)
            {
                setVisible(false);
                setVisible(true);
            }
            else if (option==2)
            {
                setVisible(false);
                setVisible(true);
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableShowAllDataCustomer;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldCustomerID;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhoneNo;
    private javax.swing.JTextField jTextFieldPostelCode;
    private javax.swing.JTextField jTextFieldProvince;
    // End of variables declaration//GEN-END:variables
}
